#### 1. Create a function that transposes a 2D matrix.
**Examples:**<br>

transpose_matrix([<br>
  &emsp;[1, 1, 1],<br>
  &emsp;[2, 2, 2],<br>
  &emsp;[3, 3, 3]<br>
]) ➞ [<br>
  &emsp;[1, 2, 3],<br>
  &emsp;[1, 2, 3],<br>
  &emsp;[1, 2, 3]<br>
]<br>

transpose_matrix([<br>
  &emsp;[5, 5],<br>
  &emsp;[6, 7],<br>
  &emsp;[9, 1]<br>
]) ➞ [<br>
  &emsp;[5, 6, 9],<br>
  &emsp;[5, 7, 1]<br>
]

In [2]:
import numpy as np

def transpose_matrix(matrix):
    print(f'transpose_matrix({matrix}) ➞ {np.array(matrix).T}')
transpose_matrix([[1, 1, 1],[2, 2, 2],[3, 3, 3]])
transpose_matrix([[5, 5],[6, 7],[9, 1]])

transpose_matrix([[1, 1, 1], [2, 2, 2], [3, 3, 3]]) ➞ [[1 2 3]
 [1 2 3]
 [1 2 3]]
transpose_matrix([[5, 5], [6, 7], [9, 1]]) ➞ [[5 6 9]
 [5 7 1]]


#### 2. Create a function that determines whether a string is a valid hex code.
A hex code must begin with a pound key # and is exactly 6 characters in length. Each character must be a digit from 0-9 or an alphabetic character from A-F. All alphabetic characters may be uppercase or lowercase.

**Examples:**<br>
is_valid_hex_code("#CD5C5C") ➞ True<br>
is_valid_hex_code("#EAECEE") ➞ True<br>
is_valid_hex_code("#eaecee") ➞ True<br>

is_valid_hex_code("#CD5C58C") ➞ False<br>
\# Length exceeds 6<br>

is_valid_hex_code("#CD5C5Z") ➞ False<br>
\# Not all alphabetic characters in A-F<br>

is_valid_hex_code("#CD5C&C") ➞ False<br>
\# Contains unacceptable character<br>

is_valid_hex_code("CD5C5C") ➞ False<br>
\# Missing #<br>

In [7]:
def is_valid_hex_code(hex):
    flag=True
    valid_hex = '#0123456789abcdef'
    for char in hex.lower():
        if char not in valid_hex or hex[0]!='#' or len(hex[1:]) != 6:
            flag=False
            break
    print(f'is_valid_hex_code({hex}) ➞ {flag}')

is_valid_hex_code("#CD5C5C")
is_valid_hex_code("#EAECEE")
is_valid_hex_code("#eaecee")
is_valid_hex_code("#CD5C58C")
is_valid_hex_code("#CD5C5Z")
is_valid_hex_code("#CD5C&C")
is_valid_hex_code("CD5C5C")

is_valid_hex_code(#CD5C5C) ➞ True
is_valid_hex_code(#EAECEE) ➞ True
is_valid_hex_code(#eaecee) ➞ True
is_valid_hex_code(#CD5C58C) ➞ False
is_valid_hex_code(#CD5C5Z) ➞ False
is_valid_hex_code(#CD5C&C) ➞ False
is_valid_hex_code(CD5C5C) ➞ False


#### 3. Given a list of math equations (given as strings), return the percentage of correct answers as a string. Round to the nearest whole number.
**Examples:**<br>
mark_maths(["2+2=4", "3+2=5", "10-3=3", "5+5=10"]) ➞ "75%"<br>
mark_maths(["1-2=-2"]), "0%"<br>
mark_maths(["2+3=5", "4+4=9", "3-1=2"]) ➞ "67%"

In [8]:
import math
def mark_maths(in_list):
    out_list = []
    for ele in in_list:
        ele = ele.split("=")
        out_list.append(eval(ele[0]) == int(ele[1])) 
    print(f'mark_maths({in_list}) ➞ {str(math.ceil((sum(out_list)/len(out_list))*100))}%')
        
mark_maths(["2+2=4", "3+2=5", "10-3=3", "5+5=10"])
mark_maths(["1-2=-2"])
mark_maths(["2+3=5", "4+4=9", "3-1=2"])

mark_maths(['2+2=4', '3+2=5', '10-3=3', '5+5=10']) ➞ 75%
mark_maths(['1-2=-2']) ➞ 0%
mark_maths(['2+3=5', '4+4=9', '3-1=2']) ➞ 67%


#### 4. There are two players, Alice and Bob, each with a 3-by-3 grid. A referee tells Alice to fill out one particular row in the grid (say the second row) by putting either a 1 or a 0 in each box, such that the sum of the numbers in that row is odd. The referee tells Bob to fill out one column in the grid (say the first column) by putting either a 1 or a 0 in each box, such that the sum of the numbers in that column is even.
Alice and Bob win the game if Alice’s numbers give an odd sum, Bob’s give an even sum, and (most important) they’ve each written down the same number in the one square where their row and column intersect.

**Examples:**<br>
magic_square_game([2, "100"], [1, "101"]) ➞ False<br>
magic_square_game([2, "001"], [1, "101"]) ➞ True<br>
magic_square_game([3, "111"], [2, "011"]) ➞ True<br>
magic_square_game([1, "010"], [3, "101"]) ➞ False<br>
\# Two lists, Alice [row, "her choice"], Bob [column, "his choice"]

In [9]:
def magic_square_game(in_one,in_two):
    output = False
    if in_two[1][in_one[0]-1] == in_one[1][in_two[0]-1]:
        output = True
    print(f'magic_square_game{in_one,in_two} ➞ {output}')
    
magic_square_game([2, "100"], [1, "101"])
magic_square_game([2, "001"], [1, "101"]) 
magic_square_game([3, "111"], [2, "011"]) 
magic_square_game([1, "010"], [3, "101"]) 

magic_square_game([2, '100'], [1, '101']) ➞ False
magic_square_game([2, '001'], [1, '101']) ➞ True
magic_square_game([3, '111'], [2, '011']) ➞ True
magic_square_game([1, '010'], [3, '101']) ➞ False


#### 5. From point A, an object is moving towards point B at constant velocity va (in km/hr). From point B, another object is moving towards point A at constant velocity vb (in km/hr). Knowing this and the distance between point A and B (in km), write a function that returns how much time passes until both objects meet.
Format the output like this: "2h 23min 34s"

**Examples:**<br>
lets_meet(100, 10, 30) ➞ "2h 30min 0s"<br>
lets_meet(280, 70, 80) ➞ "1h 52min 0s"<br>
lets_meet(90, 75, 65) ➞ "0h 38min 34s"

In [10]:
import math
def lets_meet(in_dist,in_va,in_vb):
    total_time = in_dist/(in_va+in_vb)
    Hours = math.floor(total_time) 
    Minutes = math.floor((total_time-Hours)*60)
    Seconds = math.floor(((((total_time)-Hours)*60)-Minutes)*60)
    print(f'lets_meet{in_dist,in_va,in_vb} ➞ {Hours}h {Minutes}min {Seconds}s')
    
lets_meet(100, 10, 30)
lets_meet(280, 70, 80)
lets_meet(90, 75, 65)

lets_meet(100, 10, 30) ➞ 2h 30min 0s
lets_meet(280, 70, 80) ➞ 1h 52min 0s
lets_meet(90, 75, 65) ➞ 0h 38min 34s
